name: Sanjay - GitHub Actions Learning

on:
  push:
    branches:
      - github-actions-tutorial

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Sanjay! My first GitHub Action is running."
